apiVersion: apps/v1
kind: Deployment
metadata: 
 name: myapp-deploy
spec: 
 replicas: 3
 selector: 
  matchLabels:
   app: myapp
 template:
  metadata:
   labels:
    app: myapp
  spec:
   containers:
    - name: myapp
      image: prg10:latest
      imagePullPolicy: Never
      ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
 name: myapp-service
spec: 
 type: NodePort
 selector:
  app: myapp
 ports:
  - port: 80
    targetPort: 8080


